source 'https://rubygems.org'
gem 'dotenv'
gem 'faker'
gem 'sinatra', '>= 2.2.0'
gem 'sinatra-contrib', '>= 2.2.0'
gem 'rack-contrib'
gem 'facets'
gem 'twilio-ruby'
gem 'thin'
gem 'nokogiri', '>= 1.12.5'
